# Generated by Django 5.2.6 on 2025-09-29 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('templates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Document name or identifier', max_length=255)),
                ('file', models.FileField(help_text='Original uploaded document', upload_to='documents/')),
                ('extracted_data', models.JSONField(default=dict, help_text='Extracted structured data based on template fields')),
                ('text_version', models.TextField(blank=True, help_text='Raw extracted text for general OCR mode', null=True)),
                ('confidence_score', models.FloatField(blank=True, help_text='OCR confidence score (0.0 - 1.0)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending Processing'), ('processing', 'Processing'), ('completed', 'Processing Complete'), ('failed', 'Processing Failed'), ('reviewed', 'Human Reviewed')], default='pending', max_length=20)),
                ('processing_type', models.CharField(choices=[('template', 'Template-based Extraction'), ('general', 'General Text Extraction')], default='general', max_length=20)),
                ('template', models.ForeignKey(blank=True, help_text='Template used for structured extraction (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, to='templates.template')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(help_text='Processing step name', max_length=100)),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed')], default='started', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Log message or error details')),
                ('processing_time', models.FloatField(blank=True, help_text='Time taken for this step (seconds)', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_logs', to='documents.document')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
