# Generated by Django 5.2.6 on 2025-10-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='excel_file',
            field=models.FileField(blank=True, help_text='Populated Excel file with extracted data', null=True, upload_to='documents/excel/'),
        ),
    ]
