# Generated by Django 5.2.6 on 2025-10-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_excel_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='excel_data',
            field=models.BinaryField(blank=True, help_text='Populated Excel file data (stored in DB)', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='excel_name',
            field=models.CharField(blank=True, help_text='Excel filename', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='file_data',
            field=models.BinaryField(blank=True, help_text='Original document file data (stored in DB)', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='file_name',
            field=models.CharField(blank=True, help_text='Original filename', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='file_size',
            field=models.IntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='file_type',
            field=models.CharField(blank=True, help_text='File MIME type', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='excel_file',
            field=models.FileField(blank=True, help_text='Populated Excel file with extracted data - deprecated', null=True, upload_to='documents/excel/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, help_text='Original uploaded document - deprecated', null=True, upload_to='documents/'),
        ),
    ]
