# Generated by Django 5.2.6 on 2025-09-29 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TextDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Document title', max_length=255)),
                ('original_file', models.FileField(blank=True, help_text='Original uploaded file (PDF/image)', null=True, upload_to='editor/originals/')),
                ('raw_extracted_text', models.TextField(blank=True, help_text='Raw text extracted by OCR engine')),
                ('edited_text', models.TextField(blank=True, help_text='Text after user editing and corrections')),
                ('text_format', models.CharField(choices=[('plain', 'Plain Text'), ('markdown', 'Markdown'), ('html', 'HTML'), ('rich', 'Rich Text')], default='plain', help_text='Format of the edited text', max_length=20)),
                ('ocr_confidence', models.FloatField(blank=True, help_text='Average OCR confidence score', null=True)),
                ('ocr_engine_used', models.CharField(blank=True, help_text='OCR engine used for extraction', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('reviewing', 'Under Review'), ('completed', 'Completed'), ('published', 'Published')], default='draft', max_length=20)),
                ('last_exported_at', models.DateTimeField(blank=True, null=True)),
                ('export_count', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Text Document',
                'verbose_name_plural': 'Text Documents',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ExportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_format', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Microsoft Word'), ('txt', 'Plain Text'), ('html', 'HTML'), ('markdown', 'Markdown')], max_length=20)),
                ('exported_file', models.FileField(blank=True, help_text='Generated export file', null=True, upload_to='editor/exports/')),
                ('exported_at', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.IntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('exported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_history', to='editor.textdocument')),
            ],
            options={
                'verbose_name': 'Export History',
                'verbose_name_plural': 'Export History',
                'ordering': ['-exported_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField()),
                ('text_content', models.TextField()),
                ('change_summary', models.CharField(blank=True, help_text='Brief summary of changes made', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='editor.textdocument')),
            ],
            options={
                'verbose_name': 'Document Version',
                'verbose_name_plural': 'Document Versions',
                'ordering': ['-version_number'],
                'unique_together': {('document', 'version_number')},
            },
        ),
    ]
