# Generated by Django 5.2.6 on 2025-09-30 15:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exporthistory',
            name='document',
        ),
        migrations.RemoveField(
            model_name='exporthistory',
            name='exported_by',
        ),
        migrations.AlterModelOptions(
            name='textdocument',
            options={'ordering': ['-created_at'], 'verbose_name': 'Text Document', 'verbose_name_plural': 'Text Documents'},
        ),
        migrations.RemoveField(
            model_name='textdocument',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='textdocument',
            name='edited_text',
        ),
        migrations.RemoveField(
            model_name='textdocument',
            name='export_count',
        ),
        migrations.RemoveField(
            model_name='textdocument',
            name='last_exported_at',
        ),
        migrations.RemoveField(
            model_name='textdocument',
            name='ocr_confidence',
        ),
        migrations.RemoveField(
            model_name='textdocument',
            name='ocr_engine_used',
        ),
        migrations.RemoveField(
            model_name='textdocument',
            name='raw_extracted_text',
        ),
        migrations.RemoveField(
            model_name='textdocument',
            name='status',
        ),
        migrations.RemoveField(
            model_name='textdocument',
            name='text_format',
        ),
        migrations.AddField(
            model_name='textdocument',
            name='confidence_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='textdocument',
            name='extracted_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='textdocument',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='textdocument',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='textdocument',
            name='original_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/editor/'),
        ),
        migrations.AlterField(
            model_name='textdocument',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='DocumentVersion',
        ),
        migrations.DeleteModel(
            name='ExportHistory',
        ),
    ]
