# Generated by Django 5.2.6 on 2025-10-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0002_alter_template_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='excel_template_data',
            field=models.BinaryField(blank=True, help_text='Generated Excel template (stored in DB)', null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='excel_template_name',
            field=models.CharField(blank=True, help_text='Excel template filename', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='file_data',
            field=models.BinaryField(blank=True, help_text='Original template file data (stored in DB)', null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='file_name',
            field=models.CharField(blank=True, help_text='Original filename', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='file_size',
            field=models.IntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='file_type',
            field=models.CharField(blank=True, help_text='File MIME type', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='visualization_data',
            field=models.BinaryField(blank=True, help_text='Detection visualization image (stored in DB)', null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='visualization_name',
            field=models.CharField(blank=True, help_text='Visualization filename', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='file',
            field=models.FileField(blank=True, help_text='Original template file (PDF/image) - deprecated', null=True, upload_to='templates/'),
        ),
    ]
