# Generated by Django 5.2.6 on 2025-09-29 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OCRConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Configuration name', max_length=100, unique=True)),
                ('ocr_engine', models.CharField(choices=[('tesseract', 'Tesseract OCR'), ('easyocr', 'EasyOCR'), ('google_vision', 'Google Cloud Vision API'), ('azure_form', 'Azure Form Recognizer')], default='tesseract', max_length=20)),
                ('language_code', models.CharField(default='eng', help_text='OCR language code', max_length=10)),
                ('dpi_setting', models.IntegerField(default=300, help_text='DPI for image preprocessing')),
                ('confidence_threshold', models.FloatField(default=0.6, help_text='Minimum confidence for text recognition')),
                ('apply_denoising', models.BooleanField(default=True)),
                ('apply_deskewing', models.BooleanField(default=True)),
                ('enhance_contrast', models.BooleanField(default=True)),
                ('template_matching_threshold', models.FloatField(default=0.8, help_text='Threshold for template field matching')),
                ('is_default', models.BooleanField(default=False, help_text='Use as default configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OCR Configuration',
                'verbose_name_plural': 'OCR Configurations',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(help_text='Unique task identifier', max_length=100, unique=True)),
                ('task_type', models.CharField(choices=[('template_extract', 'Template Structure Extraction'), ('document_process', 'Document Processing'), ('general_ocr', 'General OCR Processing')], max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('progress_percentage', models.IntegerField(default=0, help_text='Completion percentage (0-100)')),
                ('current_step', models.CharField(blank=True, help_text='Current processing step', max_length=100)),
                ('result_data', models.JSONField(default=dict, help_text='Task result data')),
                ('error_message', models.TextField(blank=True, help_text='Error message if failed')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Processing Task',
                'verbose_name_plural': 'Processing Tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
