# Generated by Django 5.2.6 on 2025-09-30 15:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_processing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ocrconfiguration',
            options={'verbose_name': 'OCR Configuration', 'verbose_name_plural': 'OCR Configurations'},
        ),
        migrations.RenameField(
            model_name='ocrconfiguration',
            old_name='apply_denoising',
            new_name='enable_preprocessing',
        ),
        migrations.RemoveField(
            model_name='ocrconfiguration',
            name='apply_deskewing',
        ),
        migrations.RemoveField(
            model_name='ocrconfiguration',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='ocrconfiguration',
            name='dpi_setting',
        ),
        migrations.RemoveField(
            model_name='ocrconfiguration',
            name='enhance_contrast',
        ),
        migrations.RemoveField(
            model_name='ocrconfiguration',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='ocrconfiguration',
            name='language_code',
        ),
        migrations.RemoveField(
            model_name='ocrconfiguration',
            name='name',
        ),
        migrations.RemoveField(
            model_name='ocrconfiguration',
            name='ocr_engine',
        ),
        migrations.RemoveField(
            model_name='ocrconfiguration',
            name='template_matching_threshold',
        ),
        migrations.RemoveField(
            model_name='processingtask',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='processingtask',
            name='current_step',
        ),
        migrations.RemoveField(
            model_name='processingtask',
            name='result_data',
        ),
        migrations.RemoveField(
            model_name='processingtask',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='processingtask',
            name='status',
        ),
        migrations.RemoveField(
            model_name='processingtask',
            name='task_id',
        ),
        migrations.RemoveField(
            model_name='processingtask',
            name='task_type',
        ),
        migrations.AddField(
            model_name='ocrconfiguration',
            name='engine_preference',
            field=models.CharField(choices=[('tesseract', 'Tesseract'), ('easyocr', 'EasyOCR')], default='tesseract', max_length=20),
        ),
        migrations.AddField(
            model_name='ocrconfiguration',
            name='max_file_size_mb',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='processingtask',
            name='confidence_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='processingtask',
            name='file_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='processingtask',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='processingtask',
            name='result_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='processingtask',
            name='task_name',
            field=models.CharField(default='OCR Task', max_length=200),
        ),
        migrations.AlterField(
            model_name='ocrconfiguration',
            name='confidence_threshold',
            field=models.FloatField(default=50.0),
        ),
        migrations.AlterField(
            model_name='ocrconfiguration',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='processingtask',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='processingtask',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='processingtask',
            name='progress_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
